server:
  port: 9997

spring:
  application:
    name: onlyoffice

  # 数据库配置文件
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.140:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null


  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1


minio:
  endpoint: http://192.168.2.92:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: test

token:
  secret: 123456
  expire: 240 # 分钟

office:
  # 本机地址，需要注意【这个ip需要与[api]中的ip能ping通】
  ip: http://192.168.2.92:${server.port}
  # onlyoffice服务器的js文件，ip是服务器地址
  api: http://192.168.6.180:8050/web-apps/apps/api/documents/api.js
  # 交互地址
  callbackUrl: /callback?fileId=
  # 文件下载地址
  downloadUrl: /downloadFile/


  lang: zh
  logo:
    image: https://www.risencn.com/r/cms/www/default/risen/public/img/header-logo1.png
    imageEmbedded: https://www.risencn.com/r/cms/www/default/risen/public/img/header-logo1.png
    url: http://www.baidu.com
  # 回退地址
  goBack: ${office.ip}
  # 可查看类型
  viewedDocs: [.pdf,.djvu,.xps,.oxps]
  #  可编辑类型
  editedDocs: [.docx,.xlsx,.csv,.pptx,.txt,.docxf]
  # 可类型转换类型
  convertDocs: [.docm,.dotx,.dotm,.dot,.doc,.odt,.fodt,.ott,.xlsm,.xlsb,.xltx,.xltm,.xlt,.xls,.ods,.fods,.ots,.pptm,.ppt,.ppsx,.ppsm,.pps,.potx,.potm,.pot,.odp,.fodp,.otp,.rtf,.mht,.html,.htm,.xml,.epub,.fb2]

logging:
  level:
    com.onlyoffice.mapper: debug
